[project]
name = "sqitk3073project-main"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.7.0",
    "pandas>=2.0.0",
    "scikit-learn>=1.2.0",
    "streamlit>=1.32.0",
    "yfinance>=0.2.36",
]
